---
- name: Install iptables
  action: apt pkg=iptables state=present

- name: Install iptables-persistent
  action: apt pkg=iptables-persistent state=present

- name: Prevent the iptables-peristent install dialog
  shell: echo {{ item }} | debconf-set-selections creates=/etc/init.d/iptables-persistent
  with_items:
    - iptables-persistent iptables-persistent/autosave_v4 boolean true
    - iptables-persistent iptables-persistent/autosave_v6 boolean true

- name: Install or update base set of packages
  apt: name={{ item }} state=latest
  with_items:
    - iptables-persistent

- name: Render iptables (ipv4) rules
  template: src=rules.v4.j2
            dest=/etc/iptables/rules.v4
            owner=root
            group=root
            mode=0644
  notify: restart iptables-persistent

- name: Render iptables (ipv6) rules
  template: src=rules.v6.j2
            dest=/etc/iptables/rules.v6
            owner=root
            group=root
            mode=0644
  notify: restart iptables-persistent



# - name: Install ufw
#   action: apt pkg=ufw state=present

# - name: Disable ipv6
#   action: lineinfile dest=/etc/default/ufw regexp="^IPV6*" line="IPV6=no" state=present

# - name: Turn on UFW, allow all traffic
#   ufw: state=enabled policy=allow

# - name: Enable UFW logging
#   ufw: logging=on

# - name: Enable
#   ufw: rule=allow port=ssh proto=tcp

#- name: Enable rate limiting for ssh
#  ufw: rule=limit port=ssh proto=tcp
#
#- name: Enable port 80
#  ufw: rule=allow port=80 proto=tcp
#
#- name: Enable
#  ufw: rule=allow port=443 proto=tcp
#
# - name: Enable mysql on internal port only
#   ufw: rule=allow port=3306 proto=tcp interface=eth1